name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Create stub & test framework code for a given OpenAPI
      env:
        OPENAPI_FILE: https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml
        STUB_FRAMEWORK: go-server
        TEST_FRAMEWORK: go
      run: |
        docker pull openapitools/openapi-generator-cli
        docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
          -i $OPENAPI_FILE \
          -g $STUB_FRAMEWORK \
          -o /local/out/$STUB_FRAMEWORK
        docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
          -i $OPENAPI_FILE \
          -g $TEST_FRAMEWORK \
          -o /local/out/$TEST_FRAMEWORK
          
    - name: Build a Docker image for the stub framework
      env:
        STUB_FRAMEWORK: go-server
      run: |
        cd out/$STUB_FRAMEWORK
        docker build . -t openapi-stub
    
    - name: Spin up the stub image, print the IP address, hit one of the stub endpoints, then kill the stub container
      env:
        STUB_FRAMEWORK: go-server
      run: |
        CID=$(docker run -d openapi-stub:latest)
        GEN_IP=$(docker inspect --format '{{.NetworkSettings.IPAddress}}'  $CID)
        echo "Stub container $CID is accessible on IP $GEN_IP"
        docker ps
        
        # This curl command proves the stub is running, and one of its endpoints is accessible
        curl -vvvv http://$GEN_IP:8080/v2/store/inventory
        
        # Next step would normally be to run a bunch of curl commands to populate the stub data for testing purposes...
        curl -vvvv -X POST http://$GEN_IP:8080/v2/pet -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 0, \"category\": { \"id\": 0, \"name\": \"string\" }, \"name\": \"doggie\", \"photoUrls\": [ \"string\" ], \"tags\": [ { \"id\": 0, \"name\": \"string\" } ], \"status\": \"available\"}"
        curl -vvvv -X POST http://$GEN_IP:8080/v2/pet -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"id\": 1, \"category\": { \"id\": 0, \"name\": \"string\" }, \"name\": \"kitty\", \"photoUrls\": [ \"string\" ], \"tags\": [ { \"id\": 0, \"name\": \"string\" } ], \"status\": \"available\"}"

        # Now let's do a read to see if our data was loaded properly. If so, we should see some data for "doggie" and "kitty"
        curl -vvvv -X GET http://$GEN_IP:8080/v2/pet/findByStatus?status=available -H "accept: application/json"
        
        # All done - let's stop & remove the container instance
        docker stop $CID && docker rm $CID
        
    - name: All stub tests have passed - push the new stub image to the Docker registry
      run: |
        # docker push ...
        echo "Stub container image pushed to Docker registry"
